name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    # 3. Generate javadoc files
    - name: Generate Javadoc
      run: |
        mkdir -p javadoc # create folder for the documentation
        find . -name "*.java" > sources.txt # find all java files in the project
        javadoc @sources.txt -d javadoc # generate javadoc for all java files

    # 4. Publish javadoc to github actions
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./javadoc
